In [1]:
import numpy as np
import pandas as pd

In [2]:
player_kda = pd.read_csv('player_kda.csv', index_col=0)
player_kda.head(5)

   名次        选手     战队  KDA    参团率  场均击杀  最高击杀  场均死亡  最高死亡  场均助攻  最高助攻
0   1    YTG.晨晨    YTG  9.6  82.8%   5.2    11   1.2     2   6.8    11
1   2    DYG.久诚    DYG  8.8  74.7%   3.5     7   1.1     4   6.1    10
2   3     GK.青枫     GK  6.9  77.4%   3.1     9   1.5     4   7.0    14
3   4    DYG.易峥    DYG  6.6  73.4%   4.0    10   1.4     4   5.5     9
4   5  AG超玩会.笑影  AG超玩会  5.7  74.6%   2.5     7   1.6     5   6.7    15

In [5]:
player_power = pd.read_csv('player_power.csv', index_col=0)
player_power = player_power.sort_values(by='名次')
player_power.index = range(len(player_power))
player_power.head(5)

   名次        选手     输出   承伤占比   经济占比  分均输出  分均承伤  分均经济
0   1    YTG.晨晨  37.1%  13.4%  24.9%  6490  3178   730
1   2    DYG.久诚  37.6%  12.3%  21.3%  7367  2612   655
2   3     GK.青枫  31.5%  13.4%  20.4%  5244  2618   604
3   4    DYG.易峥  28.8%  17.2%  25.0%  5655  3659   769
4   5  AG超玩会.笑影  27.9%  12.8%  19.8%  4279  2574   608

In [10]:
player = pd.merge(player_kda, player_power)
player.head()

,名次,选手,战队,KDA,参团率,场均击杀,最高击杀,场均死亡,最高死亡,场均助攻,最高助攻,输出,承伤占比,经济占比,分均输出,分均承伤,分均经济
0,1,YTG.晨晨,YTG,9.6,82.8%,5.2,11,1.2,2,6.8,11,37.1%,13.4%,24.9%,6490,3178,730
1,2,DYG.久诚,DYG,8.8,74.7%,3.5,7,1.1,4,6.1,10,37.6%,12.3%,21.3%,7367,2612,655
2,3,GK.青枫,GK,6.9,77.4%,3.1,9,1.5,4,7.0,14,31.5%,13.4%,20.4%,5244,2618,604
3,4,DYG.易峥,DYG,6.6,73.4%,4.0,10,1.4,4,5.5,9,28.8%,17.2%,25.0%,5655,3659,769
4,5,AG超玩会.笑影,AG超玩会,5.7,74.6%,2.5,7,1.6,5,6.7,15,27.9%,12.8%,19.8%,4279,2574,608

In [11]:
player.describe()

,名次,KDA,场均击杀,最高击杀,场均死亡,最高死亡,场均助攻,最高助攻,分均输出,分均承伤,分均经济
count,102.000000,102.000000,102.000000,102.000000,102.000000,102.000000,102.000000,102.000000,102.000000,102.000000,102.000000
mean,51.500000,3.418627,2.152941,6.117647,2.318627,5.549020,5.211765,11.617647,3190.872549,3994.215686,582.068627
std,29.588849,1.432558,1.217749,3.022340,0.619442,1.715552,1.692224,3.487017,1584.337271,1084.498594,110.206490
min,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,913.000000,1825.000000,372.000000
25%,26.250000,2.600000,1.000000,4.000000,1.925000,5.000000,4.100000,9.250000,1834.750000,2987.500000,529.750000
50%,51.500000,3.350000,2.200000,6.000000,2.200000,6.000000,5.200000,11.500000,2886.000000,4118.000000,588.000000
75%,76.750000,4.175000,3.000000,9.000000,2.700000,7.000000,6.200000,14.000000,4645.250000,4774.250000,667.750000
max,102.000000,9.600000,5.200000,13.000000,4.200000,10.000000,11.000000,22.000000,7367.000000,6108.000000,781.000000

In [12]:
player.dtypes

名次        int64
选手       object
战队       object
KDA     float64
参团率      object
场均击杀    float64
最高击杀      int64
场均死亡    float64
最高死亡      int64
场均助攻    float64
最高助攻      int64
输出       object
承伤占比     object
经济占比     object
分均输出      int64
分均承伤      int64
分均经济      int64
dtype: object

In [13]:
player = player[['选手', 'KDA', '参团率', '分均输出', '分均承伤', '分均经济']]

In [14]:
player['参团率'] = player['参团率'].apply(lambda s: float(s[:-1]))

In [17]:
power_list = player.columns[1:]

In [18]:
player[power_list] = player[power_list].apply(lambda x: 10 * x / np.max(x))

In [19]:
player.rename(columns={'选手': 'ID',
                       '参团率': '参团',
                       '分均输出': '输出',
                       '分均承伤': '承伤',
                       '分均经济': '发育'},
             inplace=True)

In [20]:
player.head()

         ID        KDA        参团         输出        承伤        发育
0    YTG.晨晨  10.000000  8.643006   8.809556  5.203012  9.346991
1    DYG.久诚   9.166667  7.797495  10.000000  4.276359  8.386684
2     GK.青枫   7.187500  8.079332   7.118230  4.286182  7.733675
3    DYG.易峥   6.875000  7.661795   7.676123  5.990504  9.846351
4  AG超玩会.笑影   5.937500  7.787056   5.808334  4.214145  7.784891

In [21]:
player.to_csv('Data/player.csv')